/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LuhnCheck;

import org.junit.Test;
import static org.junit.Assert.*;

public class LUHNCheckDigitTest {
    @Test public void testSomeLibraryMethod() {   
        int luhn6 = LUHNCheckDigit.getLuhn("936001531002905634");   	    	
        assertTrue("someLibraryMethod should return 'true'", LUHNCheckDigit.checkLuhn("936001531002905634"+luhn6));
    }
}
